runtime: go114
service: default
main: ./cmd/

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: static/sample.txt
    upload: static/.*\.(txt)$